### ISSUE TITLE
Change the distance computation to handle geo

### ISSUE THREAD

**Issue by yamsellem** [justinethier/node-kdtree#10]
Is there a way to configure the method used to compute the distance between points so that it can be used with latitude and longitude (_and handle the curvature of the Earth_)?

We were used to have something like that (for another kdtree implementation):

``` javascript
distance: function(obj1, obj2) {
  var a = 0.5 - Math.cos((obj2.latitude - obj1.latitude) * Math.PI / 180)/2 +
    Math.cos(obj1.latitude * Math.PI / 180) * Math.cos(obj2.latitude * Math.PI / 180) *
    (1 - Math.cos((obj2.longitude - obj1.longitude) * Math.PI / 180))/2;

  return 12742 * Math.asin(Math.sqrt(a));
}
```

**Comment by justinethier** [comment]
The [kdtree](https://github.com/jtsiomb/kdtree) C library does the distance computations, so it would have to be enhanced to support another distance function. With that support, `node-kdtree` could then select which function to use.

**Comment by justinethier** [comment]
Closing as this requires changes to the underlying C library.
