### ISSUE TITLE
support node v4.x

### ISSUE THREAD

**Issue by dy93** [justinethier/node-kdtree#12]
Hi, any plains to support node v4.x?

It seems node-kdtree can not be successfully compiled in node v4.x environment due to some prototype changed.

here is npm debug log: [npm-debug.txt](https://github.com/justinethier/node-kdtree/files/38550/npm-debug.txt)

Thanks

**Comment by justinethier** [comment]
Thanks for your report. Yes, node-kdtree should support the latest version of node. However I need to find the time for this. I would take a pull request for it, or at least use it as a starting point (ideally older versions would still be supported, too).

**Comment by dy93** [comment]
OK, thank you

**Comment by GuillaumeLeclerc** [comment]
any news ?

**Comment by justinethier** [comment]
@GuillaumeLeclerc No but would be happy to accept a pull request :)

**Comment by bschlenk** [comment]
Sent pull request, working on node 4.6+ https://github.com/justinethier/node-kdtree/pull/13

**Comment by justinethier** [comment]
Thank you - version 0.1.1 has been released with support for node 4.6+
