### ISSUE TITLE
feature k-nearest?

### ISSUE THREAD

**Issue by Andi-Lo** [justinethier/node-kdtree#16]
Hey,

is there the possibility obtaining the 2 closest points?
If not, is it possible to remove a point from the kdtree so I could perform the `tree.nearest` query twice (without getting the same point twice).

Thanks

**Comment by justinethier** [comment]
Unfortunately the underlying C library does not support either function: https://github.com/jtsiomb/kdtree

You could file an issue over there, or submit a pull request to add one of those features.

With regard to node-kdtree you could build a new tree with all of the points except the one you found, but obviously that solution isn't very efficient.

**Comment by Andi-Lo** [comment]
Okay I see,  

never the less thanks for the fast information 👍
