### ISSUE TITLE
Performance drop since 0.12

### ISSUE THREAD

**Issue by yamsellem** [justinethier/node-kdtree#9]
We've found a performance drop in our production code when migrating to node 0.12.
Here is a benchmark that reproduces it:

``` javascript
var kd = require('kdtree');
var Benchmark = require('benchmark');

var tree = new kd.KDTree(2);

tree.insert(48, 2, 'France');
tree.insert(48.856614, 2.352221948, 'Paris');
tree.insert(47.872834, -3.920734, 'Concarneau');

var suite = new Benchmark.Suite();
suite.add('Concarneau', function() {
    tree.nearest(47.8, -3.9)
})
suite.add('Paris', function() {
    tree.nearest(65, 15)
})
.on('cycle', function(event) {
    console.log(String(event.target));
})
.run({ 'async': true });
```

**On node 0.10.24 (_tested on 0.10.39 with similar results_)**

```
Concarneau x 709,237 ops/sec ±1.78% (88 runs sampled)
Paris x 682,274 ops/sec ±1.51% (89 runs sampled)
```

**On node 0.12.6 (_tested on 0.12.0 with similar results_)**

```
Concarneau x 421,800 ops/sec ±2.06% (88 runs sampled)
Paris x 424,481 ops/sec ±3.29% (93 runs sampled)
```

Any idea on the matter?

**Comment by justinethier** [comment]
Were you using the same version of node-kdtree on both versions of node?

**Comment by yamsellem** [comment]
Yep, it's 0.1.0 on both.

**Comment by justinethier** [comment]
Most likely the performance difference is due to a change in Node then, as node-kdtree was unchanged.

**Comment by yamsellem** [comment]
Agreed.
But, this situation may benefit from a performa

**Comment by yamsellem** [comment]
Agreed.
But, this situation may benefit from a performance analysis to avoid node 0.12 pitfalls (which I sadly ignore right now), don't you think?
